### ISSUE TITLE
FileNotFoundError: Sandbox server didn't startup

### ISSUE THREAD

**Issue by anjalirai-intel** [karkason/pywinsandbox#14] opened 2020-08-05 05:24 UTC
While creating the sandbox got following error:

sandbox = winsandbox.new_sandbox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\winsandbox\launch.py", line 34, in new_sandbox
    return OnlineSandbox(config)
  File "C:\Python37\lib\site-packages\winsandbox\sandbox.py", line 41, in __init__
    self._connection_tuple = session.connect_to_sandbox()
  File "C:\Python37\lib\site-packages\winsandbox\session\online_session.py", line 107, in connect_to_sandbox
    raise FileNotFoundError("Sandbox server didn't startup")
FileNotFoundError: Sandbox server didn't startup

**Comment by thommyho** [comment] 2021-03-04 18:25
Hi*,
the issue is the execution of the target.py script in https://github.com/karkason/pywinsandbox/blob/1316bd046b66abce8c7c565eb55cd26309585e8a/winsandbox/session/online_session.py in lines

https://github.com/karkason/pywinsandbox/blob/1316bd046b66abce8c7c565eb55cd26309585e8a/winsandbox/session/online_session.py#L58-L63

The call for the remote rpc fails, because calling it like python -m winsandbox.target fails with an wmi error.

A working (but hacky) fix is the resolve the path to target.py and pass directly. This works.
I attached the file.

Greetings, Thomas
[online_session.zip](https://github.com/karkason/pywinsandbox/files/6085806/online_session.zip)

**Comment by Beanecessar** [comment] 2022-08-19 13:51
It is seems a bug. This issue occurs when running "python.exe -m winsandbox.target" in sandbox, BUT by this way, it will import winsandbox first. When import winsandbox it will check whether or not the optional feature of windows sandboxes is enabled and absolutely failed and raise an error.
The easiest way to fix this is comment following code out in launch.py.
`
# Do not allow importing if the feature isn't enabled
if 'pytest' not in sys.modules:
    verify_sandbox_feature_is_enabled()
`

**Comment by karkason** [comment] 2022-08-30 18:58
> 

I looked into this issue and it doesn't reproduce for me. In any case, in #15 I change it so I run the script manually as @thommyho suggested.



> Hi*, the issue is the execution of the target.py script in https://github.com/karkason/pywinsandbox/blob/1316bd046b66abce8c7c565eb55cd26309585e8a/winsandbox/session/online_session.py in lines
> 
> https://github.com/karkason/pywinsandbox/blob/1316bd046b66abce8c7c565eb55cd26309585e8a/winsandbox/session/online_session.py#L58-L63
> 
> The call for the remote rpc fails, because calling it like python -m winsandbox.target fails with an wmi error.
> 
> A working (but hacky) fix is the resolve the path to target.py and pass directly. This works. I attached the file.
> 
> **And virtual environments doens't seem to be working because the mapped folder is the python directory with the symlinks - This I couldn't fix - I used a normal python installation**
> 
> Greetings, Thomas
> 
> [online_session.zip](https://github.com/karkason/pywinsandbox/files/6085819/online_session.zip)

Hey Thomas, thank you for your great suggestion.
In #15 I also started to support virtual environments due to your request.

**Comment by karkason** [comment] 2022-08-30 19:01
Also - I'm very sorry for the delay! Hope fixing these issues is still relevant.

**Comment by karkason** [comment] 2022-09-01 08:44
And Version 1.3.0 just released should fix this :)
Closing this issue.

**Comment by HydraDragonAntivirus** [comment] 2024-06-21 19:48
Still same

**Closed** 2024-06-26 05:22 UTC
Labels: bug

**Comment by karkason** [comment] 2024-06-26 05:26
Hey @HydraDragonAntivirus, I just published version v1.4.0. Can you check if the issue is fixed for you? Thanks! :)
